spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/davena
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect